### ISSUE TITLE
The input data format for csdR

### ISSUE THREAD

**Issue by Rohit-Satyam** [AlmaasLab/csdR#2]
Hi Developers

I wish to use your package. I have raw counts for two samples (control vs knockout) each with 2 biological replicate (i.e. 4 feature count files). But I am not sure how to give these 4 files to `run_csd` function. While viewing the data that's provided with the package I realize the counts are not raw counts but instead some non-integer values with signs.

```r
> sick_expression[1:10,1:10]
                 TMEM187       IKZF1      TRPV1     CYP2A6       RYR2
TCGA.DJ.A13L  0.25886910  1.31385680 -0.1271020 -0.6834881 -0.4114891
TCGA.DE.A4M9  0.59208636 -1.47097100  1.2461969  0.4717787  1.2144106
TCGA.J8.A3O1 -0.19256716 -0.72812927  0.4885138 -0.7809972 -0.3792373
TCGA.ET.A39K  1.31385680  0.05221925 -1.0537053 -0.5627220 -0.4006925
TCGA.4C.A93U -3.02590166  0.74770917  0.9013970  0.8291135 -0.6524206
TCGA.ET.A25I  0.59802017  0.61594986 -0.5053870  0.4114891  0.2588691
TCGA.ET.A2MZ  0.08710257 -0.21795197 -0.1925672 -0.4885138 -0.4829205
TCGA.EM.A3AK -0.30022446  0.20778210 -0.7742712 -0.8082633  0.3158622
TCGA.FK.A4UB -1.40127989 -1.22486871 -0.5395762 -1.7073658 -0.1522012
TCGA.BJ.A28X -0.83614405  2.44768351 -0.6340798 -0.2434780  1.7181407
                   CDK12     OGFRL1       ATAD1      PPDPFL        LATS1
TCGA.DJ.A13L -0.32633023  0.7477092  0.06217758 -0.09958441  0.107080851
TCGA.DE.A4M9  0.78775867 -1.9593282 -0.12710197 -0.09958441  0.057197707
TCGA.J8.A3O1  1.78740479  0.6340798  1.86648724 -0.09958441  3.025901663
TCGA.ET.A39K -1.65625689  0.5224053 -1.99440254 -0.09958441 -1.763368412
TCGA.4C.A93U  0.51671591  1.5323592  0.93936016 -0.09958441  0.947116194
TCGA.ET.A25I -0.61594986 -0.7675800  0.05719771 -0.09958441 -0.460695126
TCGA.ET.A2MZ  0.02237138  0.5338351  0.33157761 -0.09958441  0.499746840
TCGA.EM.A3AK -0.13713116  1.7181407  0.87923079 -0.09958441  0.002485504
TCGA.FK.A4UB -1.74030965 -0.6647705 -0.71522984 -0.09958441 -0.347375322
TCGA.BJ.A28X  1.36253454  1.4283268 -0.30022446 -0.09958441  0.556907718
```

In the vignette, you say `The expression values are coded as continuous numerical values which are comparable between samples. ` So how do I convert my raw counts to continuous values (Do you suggest using normalised reads from DESEq2)? Besides, how do I handle biological replicates.

**Comment by yaccos** [comment]
Dear Robit,

Thank you for your request. The function `run_csd()` accepts two numeric matrices, one for the case samples and one for the control samples, this is: You should concatenate the control samples into one matrix by row (make sure the genes match) and the knockout samples into another. CSD is designed to be used with normalized data, but you can still use raw count data if you really want to. Keep in mind though that you may obtain misleading results if you use raw counts and there is large variety in the total number of reads.

You should also keep in mind the sample size. Having only 2 samples in each cohort is insufficient for statistical power. Personally, if I was to design an experiment, I would recommend having at least 100 samples in each cohort, but would consider 50 samples acceptable.

With best regards
Jakob

**Comment by Rohit-Satyam** [comment]
Thanks. So it means I can't use it for RNASeq experiment that have 2-3 biological replicates and that csdR is only meant to analyze bigdata like TCGA.

**Comment by yaccos** [comment]
Unfortuntately, yes. `csdR` compares each possible pair of genes (hundreds of millions). In order to get a sufficient signal-to-noise ratio, it requires more samples than most experimentalists can produce themselves.  The original motiation of CSD was to be used for large-scale clinical studies in order to pinpoint the genetic basis for diseases.
